### PR TITLE
Use read() instead of sysread() where mode is ':utf8'

### PR DESCRIPTION
**Pull request by jkeenan**
For perl-5.30 compatibility.

### CODE REVIEW

**Comment by jkeenan** [comment]
Note, when run against perl5 blead, this will address one failure in t/binmode.t -- but there will still be a failure where write_file() internally calls syswrite.

**Comment by jkeenan** [comment]
If parts of this p.r. are acceptable but I'm drawing the p.r. against the wrong repository, please let me know.

**Comment by genio** [comment]
It's perfectly fine to use this repo. I'm keeping it up-to-date with perhunter/slurp so we can use the CI here. I find the CI to be extremely helpful.

This looks good for linux, but breaks Windows.  This may be helpful: https://metacpan.org/source/LEONT/File-Slurper-0.012/lib/File/Slurper.pm#L34-50

**Comment by jkeenan** [comment]
@genio I couldn't wrap my head around the File::Slurper code.  So I'm still getting test failures on Windows: https://ci.appveyor.com/project/jkeenan/slurp/build/job/8gd004nwtldmr6tm.  But I'm passing on Linux (https://travis-ci.org/jkeenan/slurp) and FreeBSD.  This may not be the best way to approach the sys* problem -- but it's a minimally viable solution (once fixed for Windows).

**Comment by genio** [comment]
@Leont Do you have any suggestions in this area?

**Comment by Leont** [comment]
> @Leont Do you have any suggestions in this area?

I would say the first patch is subtly incomplete, it should also delete the line remplementing the CRLF handing.

The second patch doesn't look correct to me (in particular I wouldn't expect the append more to be correct. It probably should be using the non-syswrite approach all the time, but that breaks the tests because those are overriding syswrite and friends -_-.

**Comment by genio** [comment]
Thanks for all of your help on this. it was taken care of in the other repo, so I'm closing this just to keep things clean

**Pull request closed without merging**
